# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: "build.$(Build.BuildNumber)"
  repository: "whatsbroken/web"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: Docker@2
            displayName: Log in to ACR
            condition: always()
            inputs:
              command: login
              containerRegistry: "aspnetinfra ACR"
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: build
              dockerfile: "src/WhatsBroken.Web/Dockerfile"
              repository: $(repository)
              buildContext: "."
              tags: |
                $(tag)
                live
          - task: Docker@2
            displayName: Push Docker Image
            condition: always()
            inputs:
              command: push
              repository: $(repository)
              tags: |
                $(tag)
                live
          - task: Docker@2
            displayName: Log out of ACR
            condition: always()
            inputs:
              command: logout
              containerRegistry: "aspnetinfra ACR"
